// src/pages/dealer/marketing/MarketingDashboard.jsx
import React, { useEffect, useState } from 'react';
import TopHeaderBar from '@/components/shared/navigation/TopHeaderBar';
import { DateRangeSelector } from '@/components/shared/navigation/DateRangeSelector';
import { MetricCard } from '@/components/shared/ui/MetricCard';
import BarChart from '@/components/shared/charts/BarChart';
import DonutChart from '@/components/shared/charts/DonutChart';
import { Link } from 'react-router-dom';
import {
  MegaphoneIcon,
  UsersIcon,
  ChartBarIcon,
  CurrencyDollarIcon,
  ArrowUpRightIcon,
  CheckCircleIcon,
} from '@heroicons/react/24/outline';
import { useCrmStore } from '@/store/crmStore';

export default function MarketingDashboard() {
  const [dateRange, setDateRange] = useState('this_quarter');
  const { marketingCampaigns, loading, fetchMarketingCampaigns, getAnalyticsData } = useCrmStore();
  const [marketingAnalytics, setMarketingAnalytics] = useState({});

  useEffect(() => {
    fetchMarketingCampaigns({ dateRange });

    const analytics = getAnalyticsData('marketingCampaigns', { dateRange });
    setMarketingAnalytics(analytics);

    const interval = setInterval(() => {
      fetchMarketingCampaigns({ dateRange });
      setMarketingAnalytics(getAnalyticsData('marketingCampaigns', { dateRange }));
    }, 60000);
    return () => clearInterval(interval);
  }, [dateRange, fetchMarketingCampaigns, getAnalyticsData]);

  const {
    totalCampaigns = 0,
    activeCampaigns = 0,
    totalLeadsGenerated = 0,
    totalSpend = 0,
    avgRoi = 0,
    leadsByCampaign = [],
    spendByCampaign = [],
  } = marketingAnalytics;


  return (
    <div className="p-6 space-y-6">
      <div className="flex flex-wrap justify-between items-center gap-4 mb-4">
        <TopHeaderBar title="Marketing Overview Dashboard" />
        <DateRangeSelector selectedRange={dateRange} onRangeChange={setDateRange} />
      </div>

      <p className="mt-1 text-gray-600">Track the effectiveness of your marketing efforts, manage campaigns, and submit reimbursement claims.</p>

      {/* KPI Cards */}
      <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-6">
        <MetricCard
          title="Total Campaigns"
          value={totalCampaigns}
          icon={MegaphoneIcon}
          loading={loading}
          trend="All campaigns"
        />
        <MetricCard
          title="Active Campaigns"
          value={activeCampaigns}
          icon={CheckCircleIcon}
          loading={loading}
          trend="Currently running"
        />
        <MetricCard
          title="Leads Generated"
          value={totalLeadsGenerated}
          icon={UsersIcon}
          loading={loading}
          trend="+10% vs last period"
        />
        <MetricCard
          title="Total Marketing Spend"
          value={`$${totalSpend.toLocaleString()}`}
          icon={CurrencyDollarIcon}
          loading={loading}
          trend="This period"
        />
        <MetricCard
          title="Average Campaign ROI"
          value={`${avgRoi.toFixed(1)}%`}
          icon={ChartBarIcon}
          loading={loading}
          trend="Across all campaigns"
          trendColor={avgRoi > 100 ? "text-green-600" : (avgRoi > 0 ? "text-blue-600" : "text-red-600")}
        />
      </div>

      {/* Charts Section */}
      <div className="grid grid-cols-1 lg:grid-cols-2 gap-8">
        <div className="bg-white p-6 rounded-lg shadow-sm border border-gray-200">
          <h2 className="text-xl font-semibold text-gray-800 mb-4">Leads Generated by Campaign</h2>
          {loading && leadsByCampaign.length === 0 ? (
             <div className="h-[300px] flex items-center justify-center text-gray-600 animate-pulse">Loading chart...</div>
          ) : leadsByCampaign.length > 0 ? (
            <BarChart
              data={leadsByCampaign}
              xAxisDataKey="name"
              barDataKey="value"
              barName="Leads"
              height={300}
              barColor="#8884d8"
            />
          ) : (
            <p className="h-[300px] flex items-center justify-center text-gray-600">No leads data for campaigns in selected period.</p>
          )}
        </div>

        <div className="bg-white p-6 rounded-lg shadow-sm border border-gray-200">
          <h2 className="text-xl font-semibold text-gray-800 mb-4">Marketing Spend by Campaign</h2>
          {loading && spendByCampaign.length === 0 ? (
             <div className="h-[300px] flex items-center justify-center text-gray-600 animate-pulse">Loading chart...</div>
          ) : spendByCampaign.length > 0 ? (
            <DonutChart
              data={spendByCampaign}
              dataKey="value"
              nameKey="name"
              height={300}
            />
          ) : (
            <p className="h-[300px] flex items-center justify-center text-gray-600">No spend data for campaigns in selected period.</p>
          )}
        </div>
      </div>

      {/* Quick Links / Navigation to detailed views */}
      <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-6">
        <div className="bg-white p-6 rounded-lg shadow-sm border border-gray-200">
          <h3 className="text-lg font-semibold text-gray-800 mb-3">Activity Plans</h3>
          <p className="text-gray-600 mb-4">Plan and manage all your marketing initiatives and activities.</p>
          <Link
            to="/dealer/marketing/activity-plan"
            className="inline-flex items-center text-blue-600 hover:text-blue-800 text-sm font-medium"
          >
            View All Plans <ArrowUpRightIcon className="ml-1 h-4 w-4" />
          </Link>
        </div>
        <div className="bg-white p-6 rounded-lg shadow-sm border border-gray-200">
          <h3 className="text-lg font-semibold text-gray-800 mb-3">Approved Activities</h3>
          <p className="text-gray-600 mb-4">Track and verify the execution of approved marketing activities.</p>
          <Link
            to="/dealer/marketing/approved-activities"
            className="inline-flex items-center text-blue-600 hover:text-blue-800 text-sm font-medium"
          >
            View Approved Activities <ArrowUpRightIcon className="ml-1 h-4 w-4" />
          </Link>
        </div>
        <div className="bg-white p-6 rounded-lg shadow-sm border border-gray-200">
          <h3 className="text-lg font-semibold text-gray-800 mb-3">Campaign Reports</h3>
          <p className="text-gray-600 mb-4">Analyze the performance and ROI of individual marketing campaigns.</p>
          <Link
            to="/dealer/marketing/reports"
            className="inline-flex items-center text-blue-600 hover:text-blue-800 text-sm font-medium"
          >
            View Reports <ArrowUpRightIcon className="ml-1 h-4 w-4" />
          </Link>
        </div>
        <div className="bg-white p-6 rounded-lg shadow-sm border border-gray-200">
          <h3 className="text-lg font-semibold text-gray-800 mb-3">Reimbursement Panel</h3>
          <p className="text-gray-600 mb-4">Submit and track co-marketing reimbursement claims from Aerion.</p>
          <Link
            to="/dealer/marketing/reimbursements"
            className="inline-flex items-center text-blue-600 hover:text-blue-800 text-sm font-medium"
          >
            Manage Claims <ArrowUpRightIcon className="ml-1 h-4 w-4" />
          </Link>
        </div>
      </div>

      <div className="bg-white p-6 rounded-lg shadow-sm border border-gray-200">
        <h2 className="text-xl font-semibold text-gray-800 mb-4">Marketing Module Views (Enterprise Grade)</h2>
        <p className="text-gray-600">
          The Marketing module is designed with comprehensive views for full control over marketing operations:
        </p>
        <ul className="list-disc list-inside ml-4 mt-2 space-y-1">
          <li>
            <strong className="text-aerion-blue">Dashboard View (Current):</strong> Aggregated KPIs and charts for overall marketing performance.
          </li>
          <li>
            <strong className="text-aerion-blue">Activity Plan View (<Link to="/dealer/marketing/activity-plan" className="text-blue-500 hover:underline">Activity Plan</Link>):</strong> For detailed planning and management of individual marketing activities.
          </li>
          <li>
            <strong className="text-aerion-blue">Approved Activities View (<Link to="/dealer/marketing/approved-activities" className="text-blue-500 hover:underline">Approved Activities</Link>):</strong> A centralized list of all activities cleared for execution, especially crucial for co-marketing with Aerion.
          </li>
          <li>
            <strong className="text-aerion-blue">Campaign Reports View (<Link to="/dealer/marketing/reports" className="text-blue-500 hover:underline">Campaign Reports</Link>):</strong> Detailed analytics on specific campaigns.
          </li>
          <li>
            <strong className="text-aerion-blue">Reimbursement Panel View (<Link to="/dealer/marketing/reimbursements" className="text-blue-500 hover:underline">Reimbursement Panel</Link>):</strong> Streamlined process for financial claims from Aerion for co-marketing efforts.
          </li>
        </ul>
      </div>
    </div>
  );
}
