// src/components/shared/utils/IconLibrary.jsx
import {
  FaPhone,
  FaEnvelope,
  FaMapMarkerAlt,
  FaCheckCircle,
  FaTimesCircle,
  FaUser,
  FaUserTie,
  FaTractor,
  FaWarehouse,
  FaChartLine,
  FaTasks,
  FaBell,
  FaUsers,
  FaFileInvoice,
  FaRocket,
  FaClipboardList,
  FaFilter,
  FaUpload,
  FaChartPie,
  FaChartBar,
  FaChartArea,
  FaCalendarAlt,
  FaArrowRight,
  FaArrowLeft,
} from 'react-icons/fa';

const IconLibrary = {
  phone: FaPhone,
  email: FaEnvelope,
  location: FaMapMarkerAlt,
  success: FaCheckCircle,
  error: FaTimesCircle,
  user: FaUser,
  dealer: FaUserTie,
  farmer: FaTractor,
  warehouse: FaWarehouse,
  performance: FaChartLine,
  tasks: FaTasks,
  reminders: FaBell,
  contacts: FaUsers,
  invoice: FaFileInvoice,
  rocket: FaRocket,
  leads: FaClipboardList,
  filters: FaFilter,
  upload: FaUpload,
  pieChart: FaChartPie,
  barChart: FaChartBar,
  trendChart: FaChartArea,
  calendar: FaCalendarAlt,
  arrowRight: FaArrowRight,
  arrowLeft: FaArrowLeft,
};

export default IconLibrary;
